//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenCaptureMVVM.Properties.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenCaptureMVVM.Properties.Strings.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP - Bitmap.
        /// </summary>
        public static string BMPFormat {
            get {
                return ResourceManager.GetString("BMPFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds.
        /// </summary>
        public static string CaptureTypeBounds {
            get {
                return ResourceManager.GetString("CaptureTypeBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Type.
        /// </summary>
        public static string CaptureTypeTitle {
            get {
                return ResourceManager.GetString("CaptureTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Area.
        /// </summary>
        public static string CaptureTypeWorking {
            get {
                return ResourceManager.GetString("CaptureTypeWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF - Graphics Interchange Format.
        /// </summary>
        public static string GIFFormat {
            get {
                return ResourceManager.GetString("GIFFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG -  Joint Photographic Experts Group.
        /// </summary>
        public static string JPGFormat {
            get {
                return ResourceManager.GetString("JPGFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG - Portable Network Graphics.
        /// </summary>
        public static string PNGFormat {
            get {
                return ResourceManager.GetString("PNGFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Screen Capture.
        /// </summary>
        public static string ScreenCaptureTitle {
            get {
                return ResourceManager.GetString("ScreenCaptureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string ScreenTypePrimary {
            get {
                return ResourceManager.GetString("ScreenTypePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string ScreenTypeSecondary {
            get {
                return ResourceManager.GetString("ScreenTypeSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Type.
        /// </summary>
        public static string ScreenTypeTitle {
            get {
                return ResourceManager.GetString("ScreenTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF - Tagged Image File Format.
        /// </summary>
        public static string TIFFormat {
            get {
                return ResourceManager.GetString("TIFFormat", resourceCulture);
            }
        }
    }
}
